language: bash
services: docker
before_install:
  - cd 17\ RestWithSpringBootUdemy\ Docker/
  - echo "We are in the Docker folder!"
before_script:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
script:
  - docker-compose build
deploy:
  provider: script
  script:
    docker push lespin/mysql-rest-with-spring-boot-udemy;
    docker push lespin/rest-with-spring-boot-udemy;
  on:
    branch: master
notifications:
  email: false
